
lab2_lin: main.o lin.o stack.o
	gcc main.o lin.o stack.o -o lab2_lin


main.o: main.c
	gcc -c -Wall -pedantic -std=gnu99 main.c

	
lin.o: lin.c
	gcc -c -Wall -pedantic -std=gnu99 lin.c
	
stack.o: stack.c
	gcc -c -Wall -pedantic -std=gnu99 stack.c
	
	
	


